"""
PPT 자동 생성 모듈
Pipeline E (요약) 결과를 python-pptx 기반 슬라이드로 변환
"""

import logging
import re
from io import BytesIO

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

logger = logging.getLogger(__name__)


def _parse_summary_sections(answer: str) -> list[dict]:
    """요약 답변을 섹션별로 파싱
    '## 제목' 또는 '**1. 제목**' 등의 패턴을 감지
    """
    sections = []
    current_title = ""
    current_body = []

    for line in answer.split("\n"):
        stripped = line.strip()
        # ## 헤더 또는 **1. 제목** 패턴
        header_match = re.match(r"^#{1,3}\s+(.+)", stripped) or re.match(
            r"^\*\*\d+\.\s*(.+?)\*\*", stripped
        )
        if header_match:
            if current_title or current_body:
                sections.append(
                    {
                        "title": current_title,
                        "body": "\n".join(current_body).strip(),
                    }
                )
            current_title = header_match.group(1).strip("*# ")
            current_body = []
        else:
            if stripped:
                # 마크다운 볼드/이탤릭 제거
                clean = re.sub(r"\*{1,2}(.+?)\*{1,2}", r"\1", stripped)
                current_body.append(clean)

    if current_title or current_body:
        sections.append(
            {
                "title": current_title,
                "body": "\n".join(current_body).strip(),
            }
        )

    # 섹션이 없으면 전체를 하나의 슬라이드로
    if not sections:
        sections = [{"title": "Summary", "body": answer[:500]}]

    return sections


def create_pptx(
    answer: str,
    title: str = "M-RAG Summary",
    subtitle: str = "",
) -> BytesIO:
    """요약 답변을 PPTX로 변환, BytesIO 반환"""
    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    # 타이틀 슬라이드
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = subtitle or "Generated by M-RAG"

    # 본문 슬라이드
    sections = _parse_summary_sections(answer)
    bullet_layout = prs.slide_layouts[1]  # Title + Content

    for section in sections:
        slide = prs.slides.add_slide(bullet_layout)
        slide.shapes.title.text = section["title"] or "Summary"

        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.clear()

        lines = section["body"].split("\n")
        for i, line in enumerate(lines):
            if not line.strip():
                continue
            # 불릿 아이템 감지 (-, *, 숫자.)
            is_bullet = bool(re.match(r"^[-*]\s", line)) or bool(
                re.match(r"^\d+\.\s", line)
            )
            clean_line = re.sub(r"^[-*]\s+", "", line)
            clean_line = re.sub(r"^\d+\.\s+", "", clean_line)

            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()

            p.text = clean_line
            p.font.size = Pt(16)
            p.alignment = PP_ALIGN.LEFT
            if is_bullet:
                p.level = 1

    # BytesIO로 저장
    output = BytesIO()
    prs.save(output)
    output.seek(0)
    return output
